
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace PI20_014_Apoteka.Entity_Framework
{

using System;
    using System.Collections.Generic;
    
public partial class Apoteka
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Apoteka()
    {

        this.Korisnik = new HashSet<Korisnik>();

        this.Narudzbenica = new HashSet<Narudzbenica>();

        this.Rezervirao = new HashSet<Rezervirao>();

        this.Zalihe = new HashSet<Zalihe>();

        this.Primka = new HashSet<Primka>();

    }


    public int ID { get; set; }

    public string Adresa { get; set; }

    public string TelefonskiBroj { get; set; }

    public int Tvrtka { get; set; }

    public string Naziv { get; set; }



    public virtual Tvrtka Tvrtka1 { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Korisnik> Korisnik { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Narudzbenica> Narudzbenica { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Rezervirao> Rezervirao { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Zalihe> Zalihe { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Primka> Primka { get; set; }

}

}
