//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PI20_014_Apoteka.Entity_Framework
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PI20_014_DBEntities : DbContext
    {
        public PI20_014_DBEntities()
            : base("name=PI20_014_DBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Apoteka> Apoteka { get; set; }
        public virtual DbSet<Dobavljac> Dobavljac { get; set; }
        public virtual DbSet<Dostupno> Dostupno { get; set; }
        public virtual DbSet<Korisnik> Korisnik { get; set; }
        public virtual DbSet<Lijek> Lijek { get; set; }
        public virtual DbSet<LoyaltyOpcije> LoyaltyOpcije { get; set; }
        public virtual DbSet<Narudzbenica> Narudzbenica { get; set; }
        public virtual DbSet<Racun> Racun { get; set; }
        public virtual DbSet<Rezervirao> Rezervirao { get; set; }
        public virtual DbSet<StavkeNarudzbenice> StavkeNarudzbenice { get; set; }
        public virtual DbSet<StavkeRacuna> StavkeRacuna { get; set; }
        public virtual DbSet<Tvrtka> Tvrtka { get; set; }
        public virtual DbSet<Uloga> Uloga { get; set; }
        public virtual DbSet<Zalihe> Zalihe { get; set; }
        public virtual DbSet<Primka> Primka { get; set; }
        public virtual DbSet<StavkePrimke> StavkePrimke { get; set; }
    }
}
