
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace PI20_014_Apoteka.Entity_Framework
{

using System;
    using System.Collections.Generic;
    
public partial class Korisnik
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Korisnik()
    {

        this.Narudzbenica = new HashSet<Narudzbenica>();

        this.Racun = new HashSet<Racun>();

        this.Rezervirao = new HashSet<Rezervirao>();

        this.Tvrtka = new HashSet<Tvrtka>();

    }


    public int ID { get; set; }

    public string KorisnickoIme { get; set; }

    public string Lozinka { get; set; }

    public string Email { get; set; }

    public Nullable<int> Uloga { get; set; }

    public Nullable<int> LoyaltyOpcije { get; set; }

    public Nullable<int> Apoteka { get; set; }

    public string Ime { get; set; }

    public string Prezime { get; set; }



    public virtual Apoteka Apoteka1 { get; set; }

    public virtual LoyaltyOpcije LoyaltyOpcije1 { get; set; }

    public virtual Uloga Uloga1 { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Narudzbenica> Narudzbenica { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Racun> Racun { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Rezervirao> Rezervirao { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Tvrtka> Tvrtka { get; set; }

}

}
