
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace PI20_014_Apoteka.Entity_Framework
{

using System;
    using System.Collections.Generic;
    
public partial class Narudzbenica
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Narudzbenica()
    {

        this.StavkeNarudzbenice = new HashSet<StavkeNarudzbenice>();

    }


    public int ID { get; set; }

    public int ID_apoteke { get; set; }

    public int ID_zaposlenika { get; set; }

    public Nullable<System.DateTime> Datum { get; set; }



    public virtual Apoteka Apoteka { get; set; }

    public virtual Korisnik Korisnik { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<StavkeNarudzbenice> StavkeNarudzbenice { get; set; }

}

}
