
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace PI20_014_Apoteka.Entity_Framework
{

using System;
    using System.Collections.Generic;
    
public partial class Rezervirao
{

    public int ID_korisnika { get; set; }

    public int ID_lijeka { get; set; }

    public int ID_apoteke { get; set; }

    public Nullable<int> Kolicina { get; set; }



    public virtual Apoteka Apoteka { get; set; }

    public virtual Korisnik Korisnik { get; set; }

    public virtual Lijek Lijek { get; set; }

}

}
